### ISSUE TITLE
Problems with displaying in fragment_details_news.xml

### ISSUE THREAD

**Issue by guttedgarden** [SESHstation/SESHstation-Android#4]
Нужно добавить `android: layout_marginTop` в `ScrollView` или `android.constraint layout.widget.ConstraintLayout` чтобы `androidx.appcompat.widget.Toolbar` не перекрывал его

Xiaomi Mi 8 (2248х1080 | 18.5:9
![photo_2021-11-29_11-09-36](https://user-images.githubusercontent.com/61158568/143832450-fe52b30b-8ade-4aba-9da9-314e48fff6cc.jpg)
)

**Comment by tic-tac-gadji** [comment]
После долгого ступора, я пришел к выводу, что проблема не в разметки страницы, а в приходящей с сервера пикчи, будем регулировать исходные изображения.

Спасибо за фидбек
