### ISSUE TITLE
Problems with displaying in fragment_home.xml

### ISSUE THREAD

**Issue by guttedgarden** [SESHstation/SESHstation-Android#5]
Отсутствует надпись _Events_ над ивентами

Xiaomi Mi 8 (2248х1080 | 18.5:9
![photo_2021-11-29_11-09-37](https://user-images.githubusercontent.com/61158568/143833219-9e23c6b4-8935-4d66-9b94-e5758511e9a5.jpg)
)

**Comment by tic-tac-gadji** [comment]
Fixed
